### ISSUE TITLE
New-AzADAppCredential - Allow you to set the displayName for the credential. CustomKeyIdentifier takes base64 encoded string

### ISSUE THREAD

**Issue by muzzar78** [Azure/azure-powershell#16870]
### Description of the new feature

I'd like to be able to set the DisplayName when creating an AD App Credential password. Currently there is a parameter for CustomKeyIdentifier but this takes a Base64 encoded string which adds complexity. 

In order to get it to get the description to display correctly in the Azure Portal, I currently convert to Base64 with the following function.

`function Base64EncodeString {
    param (
        $String
    )
    $Bytes = [System.Text.Encoding]::UTF8.GetBytes($String)
    [Convert]::ToBase64String($Bytes)
}`

and then run 

`$pw = New-AzADAppCredential -ApplicationId $app.AppId -CustomKeyIdentifier (Base64EncodeString -String "My pw id")`

Looking at the MSGraph documentation it should be possible to set a displayName when requesting a new password - https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http#examples

When using Get-AzADAppCredential, both CustomKeyIdentifier and DisplayName are returned but CustomKeyIdentifier is Base64 binary array where as DisplayName is a string

![image](https://user-images.githubusercontent.com/13233154/150083101-6d7ec6ab-b2b6-476a-a8a4-204ddba5fdc3.png)

In the portal this is what the same secrets look like the following. It seems Description is populated with either the CustomKeyIdentifier or the DisplayName value.
![image](https://user-images.githubusercontent.com/13233154/150083271-c35e55b7-4532-484e-af22-61ec13ad959d.png)

### Proposed implementation details (optional)

Here is a screenshot of the MS Graph API adding a password with displayName set

![image](https://user-images.githubusercontent.com/13233154/150084561-55aed2fa-97e1-43ff-8825-a922d09e0c6a.png)

**Comment by dingmeng-xue** [comment]
@muzzar78 , thanks for reporting. There is naming conflict. Since the beginning, `displayName` is used to specify application. It's the reason displayname of credential is not exposed. We should consider a new name for it and expose it by additional logic.

For the time being, could you add `displayName` as one key in KeyCredentials object and then create it? The example code is
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadappcredential?view=azps-7.1.0#example-1--create-key-credentials-for-application

**Comment by muzzar78** [comment]
@dingmeng-xue Thanks for the quick response. I have created an object of type Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential, set the displayName property only and then ran 

`$test = new-object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential
$test.DisplayName = 'Alternate method'`
`New-AzADAppCredential -DisplayName 'Test_PowerShell' -PasswordCredentials $test`

This returns an error - 

`New-AzADAppCredential: Cannot bind argument to parameter 'ApplicationId' because it is an empty string.`

 I have also tried using the ApplicationId parameter but get the same error.

`New-AzADAppCredential -ApplicationId $app.AppId -PasswordCredentials $test`

**Comment by VeryEarly** [comment]
> Alternate method

Hi @muzzar78 ,

After tried above scripts, I fixed the -Displayname scenario bug, however the -ApplicationId works fine in my environment, please verify, also the -ObjectId also works.

Thanks

**Comment by muzzar78** [comment]
Hi @VeryEarly, I have just tested with Az.Resources 5.3.0 and can confirm this is now working. 
```
$test = new-object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential
$test.DisplayName = 'Alternate method'
New-AzADAppCredential -DisplayName 'Test_PowerShell' -PasswordCredentials $test
```

Thanks.

**Comment by magic-happenz** [comment]
Hello, can we reopen this issue? I don´t think it is working as expected/documented. According to official cmdlet docs the object should be `Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential` and not `Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential` however it is not working like that on my machine, neither is it working in Azure Functions.

When using the -DisplayName parameter like `New-AzADAppCredential -ObjectId $ObjectId -StartDate $StartTime -EndDate $EndTime -DisplayName $DisplayName ` and error is shown `New-AzADAppCredential: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.`. Running the same command without the -DisplayName parameter runs well but the secret has no description.

Can anyone guide me to a documentation that shows how to properly set the display name of a secret?

**Comment by magic-happenz** [comment]
I can confirm that:
`$NewSecretData = New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential 
$NewSecretData.DisplayName = "test"
New-AzADAppCredential -ObjectId $OId -PasswordCredentials $NewSecretData`
is creating a secret with the desired display name. However, this is:
1. not correct according to https://docs.microsoft.com/en-us/powershell/azure/azps-msgraph-migration-changes?view=azps-7.3.2#new-azadappcredential
2. not mentioned in https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadappcredential?view=azps-7.3.2
3. not working this way in Azure Funtions. Error:
`Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]: verify that the assembly containing this type is loaded. Exception : Type : System.Management.Automation.PSArgumentException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]
`

**Comment by ioeifcss** [comment]
@magic-happenz What version of Az PowerShell are you using in your codebase?

I'm using 7.2.0 and the following works (by contrast, the same snippet did NOT work in 7.1.0):

````
$appReg = Get-AzADApplication -DisplayName $DisplayName
$passwordStartDate = Get-Date
$passwordEndDate = $passwordStartDate.AddMonths(12)

$credentialProperties = New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential
$credentialProperties.DisplayName = "F_O_O_B_A_R"
$credentialProperties.StartDateTime = $passwordStartDate
$credentialProperties.EndDateTime = $passwordEndDate

$passwordObject = New-AzADAppCredential -ObjectId $appReg.Id -PasswordCredentials $credentialProperties
````

**Comment by magic-happenz** [comment]
@ioeifcss yes I am using that version too and it works for me locally as well but it doesn't in Azure Functions and that example is also not according to official docs. Furthermore this cmdlet has a -DisplayName parameter that does not work either.

**Comment by ioeifcss** [comment]
That's really strange. Have you verified that your Function App is definitely pulling down v7.2.0? 

I've got my code excerpt working on Windows and Linux build agents, so I would have hoped it would work for you on a Function App too.

**Comment by magic-happenz** [comment]
Same here, after testing locally I was confident it will work in Functions too but it doesn't and I am using the latest version there as well. Still wondering why this is neither documented correctly nor you can simply use the -DisplayName parameter....

**Comment by kwill-MSFT** [comment]
FYI, you don't need to create a MicrosoftGraphPasswordCredential object, you can just use a Hashtable.  This is also mentioned in the docs.

```
$AADApp = Get-AzADApplication -ApplicationId $appId
$PasswordCedentials = @{
    StartDateTime = Get-Date
    EndDateTime = (Get-Date).AddYears(1)
    DisplayName = ("Secret"+(Get-Date).ToUniversalTime().ToString("yyyy'-'MM'-'dd"))
}

$Secret = New-AzADAppCredential -ApplicationObject $AADApp -PasswordCredentials $PasswordCedentials
```

The `Cannot bind argument to parameter 'ApplicationId' because it is an empty string.` error was resolved after updating to the latest Az cmdlets.

**Comment by justinvann00rt** [comment]
Can this be re-opened? Although you can set a DisplayName using the method above (creating an object or a hashtable) you can't set a CustomKeyIdentifier with that method as it's been "blocked" by MS for only god knows what reason. In that object it's a byte as opposed to a string (Base64 or otherwise). So you can only ever have a DisplayName OR a CustomKeyIdentifier, but never, it seems, both. Come on MS this is basic sh1t here.

**Comment by ChiranthanH** [comment]
It worked after following these steps
$test = new-object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential $test.DisplayName = 'Alternate method'
New-AzADAppCredential -DisplayName '<YourAPP Display Name>' -PasswordCredentials $test

**Comment by ratkinson-prh** [comment]
For those hitting this thread, the '-DisplayName' parameter is not a property field, it's a method of selecting the correct Application instead of passing the ApplicationID object. As yet, there's no '-NewDisplayName' type field other than the workarounds above.
